db:
  host: localhost
  name: application
  user: ${db.name}
  dialect: org.hibernate.dialect.PostgreSQLDialect

spring:
  config:
    import: optional:secrets.yaml
  jpa:
    open-in-view: false
    database-platform: ${db.dialect}
    properties:
      hibernate:
        dialect: ${db.dialect}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${db.host}:5432/${db.name}
    username: ${db.user}
    password: ${db.password}
  security:
    user:
      name: application

management:
  endpoints:
    web:
      exposure:
        include: '*'

kafka:
  host-name: localhost
  bootstrap-servers: ${kafka.host-name}:9092
