name: CI Build

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
#          cache: maven

      - name: Maven Settings
        uses: s4u/maven-settings-action@v2
        with:
          servers: '[{"id": "github", "username": "${GITHUB_USER_REF}", "password": "${GITHUB_TOKEN_REF}"}]'
          githubServer: false

      - name: Build with Maven
        run: mvn -B -Pgithub package --file pom.xml
        env:
          GITHUB_USER_REF: ${{ secrets.GH_USER }}
          GITHUB_TOKEN_REF: ${{ secrets.GH_TOKEN }}
